// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xygo/internal/dao/internal"
)

// uranTestableDao is the data access object for the table xy_uran_testable.
// You can define custom methods on it to extend its functionality as needed.
type uranTestableDao struct {
	*internal.UranTestableDao
}

var (
	// UranTestable is a globally accessible object for table xy_uran_testable operations.
	UranTestable = uranTestableDao{internal.NewUranTestableDao()}
)

// Add your custom methods and functionality below.
