// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xygo/internal/dao/internal"
)

// uranContactDao is the data access object for the table xy_uran_contact.
// You can define custom methods on it to extend its functionality as needed.
type uranContactDao struct {
	*internal.UranContactDao
}

var (
	// UranContact is a globally accessible object for table xy_uran_contact operations.
	UranContact = uranContactDao{internal.NewUranContactDao()}
)

// Add your custom methods and functionality below.
