// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xygo/internal/dao/internal"
)

// uranExampleDao is the data access object for the table xy_uran_example.
// You can define custom methods on it to extend its functionality as needed.
type uranExampleDao struct {
	*internal.UranExampleDao
}

var (
	// UranExample is a globally accessible object for table xy_uran_example operations.
	UranExample = uranExampleDao{internal.NewUranExampleDao()}
)

// Add your custom methods and functionality below.
