// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"xygo/internal/dao/internal"
)

// userTablegenDao is the data access object for the table xy_user_tablegen.
// You can define custom methods on it to extend its functionality as needed.
type userTablegenDao struct {
	*internal.UserTablegenDao
}

var (
	// UserTablegen is a globally accessible object for table xy_user_tablegen operations.
	UserTablegen = userTablegenDao{internal.NewUserTablegenDao()}
)

// Add your custom methods and functionality below.
